### PR TITLE
feat: redux-compat package with useStore

### PR DESCRIPTION
**Pull request by ivan-nemtinov**

### CODE REVIEW

**Comment by artalar** [comment]
`redux-compat` must includes a little more functionality and a package must contains docs and tests.

About functionality i mean compatible API for use reatom in redux, like [here](https://github.com/artalar/rtk-github-issues-example/pull/1/files#diff-314db12f3a037090af2c7a1b0d7645d1)

**Comment by ivan-nemtinov** [comment]
> `redux-compat` must includes a little more functionality and a package must contains docs and tests.
> 
> About functionality i mean compatible API for use reatom in redux, like [here](https://github.com/artalar/rtk-github-issues-example/pull/1/files#diff-314db12f3a037090af2c7a1b0d7645d1)

I plan to include docs after th

**Comment by ivan-nemtinov** [comment]
> `redux-compat` must includes a little more functionality and a package must contains docs and tests.
> 
> About functionality i mean compatible API for use reatom in redux, like [here](https://github.com/artalar/rtk-github-issues-example/pull/1/files#diff-314db12f3a037090af2c7a1b0d7645d1)

The docs will be autogenerated with my other PR, which must be finished first.
The code already contains JSDoc comments.

I propose to start the package with this functionality and then move redux DevTools to it with a separate PR, and increase package's major version to at least minor, because it will be incompatible.

**Comment by ivan-nemtinov** [comment]
> > `redux-compat` must includes a little more functionality and a package must contains docs and tests.
> > About functionality i mean compatible API for use reatom in redux, like [here](https://github.com/artalar/rtk-github-issues-example/pull/1/files#diff-314db12f3a037090af2c7a1b0d7645d1)
> 
> The docs will be autogenerated with my other PR, which must be finished first.
> The code already contains JSDoc comments.
> 
> I propose to start the package with this functionality and then add other functionality to it with a separate PR.

I'll add tests for useStore

**Comment by artalar** [comment]
@ivan-nemtinov need tests

**Comment by ivan-nemtinov** [comment]
@artalar The build is failed in observable package. The problem appears in symbol-observable module. I didn't found a quick solution how to fix this. I propose to not use symbols at all. They have no real benefits and lead to problems here and in the documentation, require a polyfill which increases bundle size. What do you think?

**Comment by artalar** [comment]
@allcontributors please add @ivan-nemtinov  for code

**Pull request merged**
