### PR TITLE
ESM module export

### LINKED ISSUE #573: [BUG] Issues in combination Sveltekit
Hey @artalar , thanks for this cool library! 

I would like to try it in combination with Svelte. For testing I started using it with sveltekit scaffold and it complaints when I try to render it. 

There seems to be an issue with "@reatom/framework" re-exports... 

```
Internal server error: Unexpected token 'export'
      at internalCompileFunction (node:internal/vm:73:18)
      at wrapSafe (node:internal/modules/cjs/loader:1176:20)
      at Module._compile (node:internal/modules/cjs/loader:1218:27)
      at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
      at Module.load (node:internal/modules/cjs/loader:1117:32)
      at Module._load (node:internal/modules/cjs/loader:958:12)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
      at ModuleJob.run (node:internal/modules/esm/module_job:194:25) (x14)
reatom/node_modules/.pnpm/@reatom+framework@3.4.6/node_modules/@reatom/framework/build/index.module.js:1
export*from"@reatom/async";export*from"@reatom/core";export*from"@reatom/effects";export*from"@reatom/hooks";export*from"@reatom/lens";export*from"@reatom/logger";export*from"@reatom/primitives";export*from"@reatom/utils";
```

Repo with reproduction: 

- https://github.com/mindreframer/reatom-sveltekit-issue/
- https://github.com/mindreframer/reatom-sveltekit-issue/blob/main/error-message.png

Is this a known issue? Some configuration settings to fix it? 

Thanks!

### LINKED ISSUE #806: Cannot use the package with Vike
When you try to import `@reatom/core` in [Vike](https://vike.dev/) (formerly `vite-ssr-plugin`) project, I've got an error:

```
SyntaxError: Unexpected token 'export'
...
┌────────────────────────────────────────────────────────────────────────────────┐
│ The error seems to be a CJS/ESM issue, see https://vike.dev/broken-npm-package │
└────────────────────────────────────────────────────────────────────────────────┘
```

There is a workaround, described on https://vike.dev/broken-npm-package page, but IMO the Reatom should just work.

## Playground
[CodeSandbox](https://codesandbox.io/p/devbox/vigorous-lederberg-9lxxxp?file=%2Frenderer%2FPageShell.tsx%3A37%2C32&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clume0aeh00053b6gzu25qvng%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clume0aeg00023b6gve7kw21x%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clume0aeg00033b6ghlazk9xi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clume0aeg00043b6gf4utqly4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clume0aeg00023b6gve7kw21x%2522%253A%257B%2522id%2522%253A%2522clume0aeg00023b6gve7kw21x%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clumeenvm00023b6fmxhsem0j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A37%252C%2522startColumn%2522%253A32%252C%2522endLineNumber%2522%253A37%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Frenderer%252FPageShell.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clumeenvm00023b6fmxhsem0j%2522%257D%252C%2522clume0aeg00043b6gf4utqly4%2522%253A%257B%2522id%2522%253A%2522clume0aeg00043b6gf4utqly4%2522%252C%2522activeTabId%2522%253A%2522clume11lq00b03b6gydkqx3x6%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clume11lq00b03b6gydkqx3x6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clume0aeg00033b6ghlazk9xi%2522%253A%257B%2522id%2522%253A%2522clume0aeg00033b6ghlazk9xi%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clume0uir004m3b6gkd3r0wre%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clume0uir004m3b6gkd3r0wre%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### LINKED ISSUE #816: Reatom doesn't work with esm packages
### What happened?

Bug with esm if we try to import reatom in esm-based package
we got an error: 
```
$ node ./dist/hello.js
file:///check-ts-issue/dist/hello.js:1
import { atom, createCtx } from '@reatom/framework';
         ^^^^
SyntaxError: Named export 'atom' not found. The requested module '@reatom/framework' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@reatom/framework';
const { atom, createCtx } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Node.js v18.16.1
error Command failed with exit code 1.

```

Here's the repo with reproduce:
https://github.com/Aetet/reatom-esm-reproduce

### Part

Package @reatom/core

### Version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by BANOnotIT**
This PR should closes #816, #806, and #573

Auxiliary materials:
1. [First mention of package.json#module in DRAFT EP](https://github.com/nodejs/node-eps/blob/4217dca299d89c8c18ac44c878b5fe9581974ef3/002-es6-modules.md#51-determining-if-source-is-an-es-module)
2. [Final EP DRAFT mentioning type=module and .mjs instead](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#32-determining-if-source-is-an-es-module)
3. [Webpack 4 usage of package.json#module, #browser and #main](https://webpack.js.org/configuration/resolve/#resolvemainfields)
4. [TypeScript's behaviour "node16"](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node16-nodenext)

### CODE REVIEW

**Comment by BANOnotIT** [comment]
Initial confusion is likely to be caused by how microbundle handles ESM building by assuming everything in package.json#module is ESM. But now it checks for package.json#type also.

**Comment by Akiyamka** [comment]
How esbuild read package.json
https://esbuild.github.io/api/#platform

**Review by artalar — DISMISSED** [review]

**Comment by artalar** [comment]
@BANOnotIT if this is ready - merge it.

**Comment by BANOnotIT** [comment]
@artalar Still can't merge it myself

**Review by artalar — APPROVED** [review]

**Pull request merged**
