### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by vkozio**

### CODE REVIEW

**Comment by artalar** [comment]
I think we need something like [that](https://github.com/artalar/reatom/blob/v1-lts/packages/core/src/shared.ts#L52-L68) (without symbol or array support)

Btw, I could tag it as `#hacktoberfest`

**Comment by vkozio** [comment]
Sorry, created this accidentally. Github is too smart sometimes) But anyway ability to use action name generator is what I'm seriously love to see) Thanks

**Comment by artalar** [comment]
Do you have a plan to make PR?

**Comment by vkozio** [comment]
Yes, just will do it proper way. This one was by mistake, sorry again)

**Pull request closed without merging**
