### PR TITLE
Update shallowEqual util

### PR DESCRIPTION
**Pull request by iminside**
Hi!
It doesn't make sense to compare all properties if somewhere in the middle there are already non-matching ones.

### CODE REVIEW

**Comment by BataevDaniil** [comment]
Possible just use 'some' and negative condition?
This condition  looks scary. 
Thanks for finding this!

**Comment by iminside** [comment]
@BataevDaniil 
Yes you are right. 
This can indeed be done through `some`. 
Fixed

**Comment by artalar** [comment]
I don't understand the difference:) what kind of behavior changed by this pr?

**Comment by iminside** [comment]
Oops :)
I have never done a more stupid PR :)

**Pull request closed without merging**
