### PR TITLE
Add reatomClock utility in @reatom/timer to operate with absolute time

### PR DESCRIPTION
**Pull request by BANOnotIT**

### CODE REVIEW

**Comment by artalar** [comment]
@BANOnotIT please, change the API to: 

```ts
reatomClock(
  options?: { updateInterval?: number, updateStart?: 'init' | 'connection' },
  name?: string
)
```

**Review by artalar — CHANGES_REQUESTED** [review]
@BANOnotIT please, change the API to: 

```ts
reatomClock(
  options?: { updateInterval?: number, updateStart?: 'init' | 'connection' },
  name?: string
)
```

**Comment by BANOnotIT** [comment]
How `updateStart = 'init'` should wok? Why `name` should be a separate positional argument if it's inside options object in other APIs?

**Comment by artalar** [comment]
@BANOnotIT 

> How updateStart = 'init' should wok?

Just like `withInit` - on first atom touch (read / update)

> Why name should be a separate positional argument

We, probably, should improve eslint to allow passing the name in the first argument. @krulod what do you think, don't it be too complex?

**Comment by BANOnotIT** [comment]
What if we just also refactor reatomTimer to accept name as second argument and deprecate name in first argument?

**Comment by BANOnotIT** [comment]
Do I understand correctly that 'init' just should not stop timer on disconnect?

**Comment by artalar** [comment]
@BANOnotIT

> Do I understand correctly that 'init' just should not stop timer on disconnect?

yep. AND the timer starts immidiatly on the first read, even if there is now subscribtion at all.

**Comment by artalar** [comment]
I still don't understand the purpose of this helper. Please, provide an example of an application that demonstrates the obvious benefits of this method.

**Pull request closed without merging**
