### PR TITLE
docs: fixed link in core.md

### PR DESCRIPTION
**Pull request by kirademiurge**
fixed broken link

### CODE REVIEW

**Comment by artalar** [comment]
Hey! Apologies for the significant delay. You are trying to edit an autogenerated file. Please make the changes here: https://github.com/artalar/reatom/blob/dda277708499778b30a2a0ae235f7db68e814f5d/packages/core/README.md?plain=1#L5. You should replace `[Main introduction](https://www.reatom.dev).` with `[Main introduction](https://www.reatom.dev/).` 🙌

**Comment by kirademiurge** [comment]
hii! i did it

**Review by artalar — APPROVED** [review]

**Comment by artalar** [comment]
@StackBlitz where are you?

**Comment by artalar** [comment]
@codeflowapp

**Comment by artalar** [comment]
@kirademiurge thanks)

**Pull request merged**
